# generated by datamodel-codegen:
#   filename:  project.json
#   timestamp: 2025-01-10T06:39:46+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class LocalResources:
    """
    Local resources required for execution.
    """

    max_cpu_cores: float | None = None
    """
    Maximum number of CPU cores.
    """
    max_memory_mb: int | None = None
    """
    Maximum amount of memory in megabytes.
    """
    min_cpu_cores: float | None = None
    """
    Minimum number of CPU cores.
    """
    min_memory_mb: int | None = None
    """
    Minimum amount of memory in megabytes.
    """


@dataclass
class TestReportItem:
    format: str | None = None
    """
    Format of test report.
    """
    path: str | None = None
    """
    Path to report file.
    """


@dataclass
class Type:
    """
    Type of artifact.
    """

    docker: dict[str, Any] | None = None
    """
    Docker image artifact.
    """
    test_report: list[TestReportItem] | None = None
    """
    Test Report
    """


@dataclass
class PostgresPlatformResource:
    """
    Postgres database.
    """

    database_id: str
    """
    Name of postgres database.
    """


@dataclass
class PlatformResource:
    """
    A platform resource need.
    """

    postgres: PostgresPlatformResource | None = None


@dataclass
class Execution:
    """
    Execution parameters.
    """

    local_resources: LocalResources | None = None
    """
    Local resources required for execution.
    """
    platform_resources: list[PlatformResource] | None = None
    """
    List of platform resources needed.
    """


@dataclass
class Artifact:
    """
    Ballista artifact. Valid artifact types are dynamically generated based on enabled plugins.
    """

    dockerfile_stage: str
    """
    Name of stage inside Dockerfile that will contain the artifact.
    """
    name: str
    """
    Unique name key of artifact.
    """
    type: Type
    """
    Type of artifact.
    """
    dockerfile: str | None = None
    """
    Name of Dockerfile, relative to project root, to find the indicated `dockerfile_stage`. Defaults to "Dockerfile" when not specified.
    """
    execution: Execution | None = None
    """
    Execution parameters.
    """


@dataclass
class Model:
    """
    Ballista Project V1 alpha.
    """

    api_version: str
    """
    Ballista Project API version.
    """
    name: str
    """
    Name of project.
    """
    artifacts: list[Artifact] | None = None
    """
    List of artifacts.
    """
    version: str | None = None
    """
    Semantic version of project.
    """
