[project]
name = "ballista-sdk"
version = "0.1.0"
description = "Ballista.build SDK for Python"
readme = "README.md"
authors = [{ name = "August Bigelow", email = "dev@atbigelow.com" }]
license = "MIT"
requires-python = ">=3.11"
dependencies = [
    "kubernetes>=32.0",
    "openapi-pydantic>=0.5.1",
    "pydantic>=2",
    "pyyaml>=6.0",
    "semver>=3.0",
    "ty>=0.0.1a32",
    "urllib3>=1.25,<3.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.9",
    "pytest>=8.3",
    "coverage>=7.7",
    "ty>=0.0.1a21",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.coverage.run]
source = ["src"]

[tool.ruff]
line-length = 120
target-version = "py311"
