# coding: utf-8

"""
    Ballista API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from ballista.api.v1alpha.models.artifact_execution_local_resources import ArtifactExecutionLocalResources
from typing import Optional, Set
from typing_extensions import Self

class ArtifactExecution(BaseModel):
    """
    ArtifactExecution
    """ # noqa: E501
    local_resources: Optional[ArtifactExecutionLocalResources] = None
    platform_resources: Optional[List[Dict[str, Any]]] = Field(default=None, description="List of platform resources needed.")
    __properties: ClassVar[List[str]] = ["local_resources", "platform_resources"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ArtifactExecution from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of local_resources
        if self.local_resources:
            _dict['local_resources'] = self.local_resources.to_dict()
        # set to None if local_resources (nullable) is None
        # and model_fields_set contains the field
        if self.local_resources is None and "local_resources" in self.model_fields_set:
            _dict['local_resources'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ArtifactExecution from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "local_resources": ArtifactExecutionLocalResources.from_dict(obj["local_resources"]) if obj.get("local_resources") is not None else None,
            "platform_resources": obj.get("platform_resources")
        })
        return _obj


